### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by alexhutman**
Lint Cython files

### CODE REVIEW

**Comment by alexhutman** [comment]
Hmm... currently running into an [OOM issue](https://github.com/alexhutman/ZeroForcingNumber/actions/runs/10180703493/job/28159474830?pr=12) during linting. Not really sure why, I'd think that building the wavefront code might require more memory. Might have to separate the linting workflow...

**Comment by alexhutman** [comment]
Okay I *think* that OOM issue will be resolved. According to [this](https://github.com/orgs/community/discussions/25288#discussioncomment-3247293), `workflow_run` can only be called on workflows existing in the default, in our case `master`, branch... 😵‍💫 So we might have to just merge and see if the linting workflow runs after `build_and_test`.

**Comment by alexhutman** [comment]
@ldeaett Sorry for the noise, thought I was ready but had to tweak some things. I think it's good now whenever you're ready. Just please don't merge yet -- next time we meet, we can do a working session where I show you how I'd clean up these commits a bit more before merging to master.

**Comment by alexhutman** [comment]
> @ldeaett Sorry for the noise, thought I was ready but had to tweak some things. I think it's good now whenever you're ready. Just please don't merge yet -- next time we meet, we can do a working session where I show you how I'd clean up these commits a bit more before merging to master.

Cancel that @ldeaett, you can merge whenever you approve. Just please rebase and merge! The commits could be worse...

**Review by ldeaett — APPROVED** [review]
Looks good!

**Pull request merged**
